#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# aliases
alias dockerip='docker ps | tail -n +2 | while read cid b; do echo -n "$cid\t"; docker inspect $cid | grep IPAddress | cut -d \" -f 4; done'

if [ -f "$HOME/bin/hub" ]; then
        alias git=hub
fi

# ssh auto completion from known_hosts file (might need to add
# "HashKnownHosts no" ~/.ssh/config)
zstyle -e ':completion::*:*:*:hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'

# source rvm if it exists
if [[ -s /usr/local/rvm/scripts/rvm ]]; then
  source /usr/local/rvm/scripts/rvm
fi

# source virtenvwrapper if it exists
if [[ -s /usr/local/bin/virtualenvwrapper.sh ]]; then
  export WORKON_HOME=$HOME/.virtualenvs
  export PROJECT_HOME=$HOME/Code
  source /usr/local/bin/virtualenvwrapper.sh
fi

# set a nicer TERM
export TERM=xterm-256color

# We're all ready :)
echo "WALRUS"

export PATH="$PATH:$HOME/.rvm/bin:$HOME/bin:$HOME/Code/jsbsim/src" # Add RVM to PATH for scripting
