require('core')
require('packages')
require('packages-config')
-- require('autocmds')
require('keymap')
--require('org-mode')
require('wiki')
require('snippy')
vim.cmd('source ~/.config/nvim/to_migrate.vim')
