#!/bin/bash

COLGOOD="#98971a"
COLBAD="#d79921"
COLDEGRADED="#458588"

IWPRESENT="$(ip link | grep wlp)"

if [[ -n "$IWPRESENT" ]]; then
    INT="$(ip link | grep wlp | awk -F: '{print $2}' | tr -d ' ')"
    SSID="$(/sbin/iwgetid -r)"
    if [[ -z "$SSID" ]]; then
        RET=" down"
		RETCOLOR=$COLBAD
    else
        SIGNAL="$(/sbin/iwconfig $INT | sed -n 's/.*Link Quality=\([0-9][0-9]*\/[0-9][0-9]*\).*/\1/p')"
        IP="$(ip addr show $INT | grep "inet " | awk '{print $2}')"
        RET=" $SIGNAL at $SSID ($IP)"
		RETCOLOR=$COLGOOD
    fi 
else
    RET=" Disabled"
    RETCOLOR=$COLBAD
fi

echo $RET
echo
echo $RETCOLOR

# #!/bin/bash

# COLGOOD="#2E9D54"
# COLBAD="#cc6666"
# COLDEGRADED="#81a2be"

# INTPRESENT="$(ip link | grep enp)"

# if [[ -n "$INTPRESENT" ]]; then
#     INT="$(ip link | grep enp | awk -F: '{print $2}' | tr -d ' ')"
#     CARRIER="$(cat /sys/class/net/$INT/carrier)"
#     if [[ "$CARRIER" -eq 0 ]]; then
#         RET=" down"
# 		RETCOLOR=$COLBAD
#     else
#         IP="$(ip addr show $INT | grep "inet " | awk '{print $2}')"
#         RET=" Connected ($IP)"
# 		RETCOLOR=$COLGOOD
#     fi 
# else
#     RET=" no interface"
#     RETCOLOR=$COLBAD
# fi

# echo $RET
# echo
# echo $RETCOLOR
